In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import models,layers

In [2]:
data=pd.read_csv('/content/insurance_data (2).csv')
data.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
x=data.drop('bought_insurance',axis=1)
y=data.bought_insurance

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [5]:
x_train_scaled=x_train.copy()
x_train_scaled['age']=x_train['age']/100
x_test_scaled=x_test.copy()
x_test_scaled['age']=x_test['age']/100

In [6]:
model=keras.Sequential([
    layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones', bias_initializer='zeros')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model=keras.Sequential([
    layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones', bias_initializer='zeros')
])

In [8]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy']


)

In [11]:
model.fit(x_train_scaled,y_train,epochs=1500,verbose=2)

Epoch 1/1500
1/1 - 0s - 41ms/step - accuracy: 0.6818 - loss: 0.6210
Epoch 2/1500
1/1 - 0s - 54ms/step - accuracy: 0.6818 - loss: 0.6209
Epoch 3/1500
1/1 - 0s - 51ms/step - accuracy: 0.6818 - loss: 0.6209
Epoch 4/1500
1/1 - 0s - 42ms/step - accuracy: 0.6818 - loss: 0.6208
Epoch 5/1500
1/1 - 0s - 46ms/step - accuracy: 0.6818 - loss: 0.6208
Epoch 6/1500
1/1 - 0s - 45ms/step - accuracy: 0.6818 - loss: 0.6207
Epoch 7/1500
1/1 - 0s - 43ms/step - accuracy: 0.6818 - loss: 0.6207
Epoch 8/1500
1/1 - 0s - 44ms/step - accuracy: 0.6818 - loss: 0.6207
Epoch 9/1500
1/1 - 0s - 43ms/step - accuracy: 0.6818 - loss: 0.6206
Epoch 10/1500
1/1 - 0s - 44ms/step - accuracy: 0.6818 - loss: 0.6206
Epoch 11/1500
1/1 - 0s - 43ms/step - accuracy: 0.6818 - loss: 0.6205
Epoch 12/1500
1/1 - 0s - 43ms/step - accuracy: 0.6818 - loss: 0.6205
Epoch 13/1500
1/1 - 0s - 43ms/step - accuracy: 0.6818 - loss: 0.6205
Epoch 14/1500
1/1 - 0s - 42ms/step - accuracy: 0.6818 - loss: 0.6204
Epoch 15/1500
1/1 - 0s - 68ms/step - accura

In [12]:
model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 1.0000 - loss: 0.4101


[0.4100762605667114, 1.0]

In [13]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[0.7197772 ],
       [0.68142545],
       [0.7250205 ],
       [0.3169804 ],
       [0.48091874],
       [0.32266814]], dtype=float32)

In [14]:
y_test

9     1
25    1
8     1
21    0
0     0
12    0
Name: bought_insurance, dtype: int64

In [15]:
coef,intersept=model.get_weights()

In [16]:
coef,intersept

(array([[2.6146636],
        [0.7959081]], dtype=float32),
 array([-1.4474962], dtype=float32))

In [17]:
def sigmoid(x):
  import math
  return 1/(1+math.exp(-x))
print(sigmoid(18))

0.9999999847700205


In [18]:
x_test

age  affordibility
9    61              1
25   54              1
8    62              1
21   26              0
0    22              1
12   27              0

In [19]:
def prediction(age,afford):
  sum_weights=coef[0]*age+coef[1]*afford+intersept
  return sigmoid(sum_weights)
prediction(.27,0)

/tmp/ipython-input-409418760.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.32266814113874637

In [21]:
prediction(.22,1)

/tmp/ipython-input-409418760.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.4809187380245219

In [23]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [24]:
def log_loss(y_true,y_predicted):
  epsilon=1e-15
  y_predicted_new=[max(i,epsilon)for i in y_predicted]
  y_predicted_new=[min(i,epsilon) for i in y_predicted_new]
  y_predicted_new=np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))



In [29]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias


In [30]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.9736899318847281, w2:0.931388810977659, bias:-0.11748951666770448, loss:17.26938819745534
Epoch:1, w1:0.9536535852311094, w2:0.8740290167758512, bias:-0.21881533456146035, loss:17.26938819745534
Epoch:2, w1:0.9393731039296969, w2:0.8271852202997496, bias:-0.3053620401943441, loss:17.26938819745534
Epoch:3, w1:0.9301932588998061, w2:0.7897792032048467, bias:-0.37884372361582785, loss:17.26938819745534
Epoch:4, w1:0.9254091137248938, w2:0.7605726653866934, bias:-0.44108236820018304, loss:17.26938819745534
Epoch:5, w1:0.9243325693598607, w2:0.738313053647322, bias:-0.49384257986251556, loss:17.26938819745534
Epoch:6, w1:0.926333296357235, w2:0.7218280753843739, bias:-0.5387319906498417, loss:17.26938819745534
Epoch:7, w1:0.930858097563688, w2:0.7100747303660235, bias:-0.5771558825717441, loss:17.26938819745534
Epoch:8, w1:0.9374354910317362, w2:0.7021560855322683, bias:-0.6103083840841516, loss:17.26938819745534
Epoch:9, w1:0.9456716791005845, w2:0.6973185496313956, bias:-0.

(np.float64(8.401351862472232),
 np.float64(1.5008804215445002),
 np.float64(-4.382056927000268))

In [32]:
coef,intersept

(array([[2.6146636],
        [0.7959081]], dtype=float32),
 array([-1.4474962], dtype=float32))